content:
  - name: homepage
    label: Homepage
    path: src/_homepage
    type: collection
    fields:
      - name: about
        label: About
        type: text
      - name: services
        label: Services
        type: text
      - name: Recent_activity
        label: Recent activity
        type: text